package com.focussound.database

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.focussound.composition.CompositionGenre
import com.focussound.data.FocusMode
import com.focussound.data.FocusSession
import com.focussound.data.SoundType

@Entity(tableName = "focus_sessions")
data class FocusSessionEntity(
    @PrimaryKey
    val id: String,
    val mode: String,
    val soundType: String,
    val durationMinutes: Int,
    val elapsedSeconds: Int,
    val startedAtMillis: Long,
    val endedAtMillis: Long,
    val focusRating: Int,
    val fatigueRating: Int,
    val brightness: Float,
    val warmth: Float,
    val movement: Float,
    val fatigueScore: Int,
    val completed: Boolean,
    val tooBright: Boolean,
    val tooMuffled: Boolean,
    val tooMuchBass: Boolean,
    val patchId: String?,
    val patchName: String?,
    val highCut: Float,
    val stereoWidth: Float,
    val rainLayerAmount: Float,
    val padLayerAmount: Float,
    val conditionSnapshotId: Long?,
    val compositionPatchId: String?,
    val compositionPatchName: String?,
    val compositionGenre: String?,
    val melodyDensity: Float,
    val rhythmDensity: Float,
    val harmonicComplexity: Float,
    val melodyAnnoying: Boolean,
    val rhythmAnnoying: Boolean,
    val harmonyLiked: Boolean,
    val tooRepetitive: Boolean,
    val focusedWell: Boolean,
    val tooDark: Boolean,
    val useAgain: Boolean
) {
    fun toDomain(): FocusSession = FocusSession(
        id = id,
        mode = enumValueOrDefault(mode, FocusMode.STUDY),
        soundType = enumValueOrDefault(soundType, SoundType.PINK),
        durationMinutes = durationMinutes,
        elapsedSeconds = elapsedSeconds,
        startedAtMillis = startedAtMillis,
        endedAtMillis = endedAtMillis,
        focusRating = focusRating,
        fatigueRating = fatigueRating,
        brightness = brightness,
        warmth = warmth,
        movement = movement,
        fatigueScore = fatigueScore,
        completed = completed,
        tooBright = tooBright,
        tooMuffled = tooMuffled,
        tooMuchBass = tooMuchBass,
        patchId = patchId,
        patchName = patchName,
        highCut = highCut,
        stereoWidth = stereoWidth,
        rainLayerAmount = rainLayerAmount,
        padLayerAmount = padLayerAmount,
        conditionSnapshotId = conditionSnapshotId,
        compositionPatchId = compositionPatchId,
        compositionPatchName = compositionPatchName,
        compositionGenre = compositionGenre?.let { enumValueOrDefault(it, CompositionGenre.AMBIENT_CODING) },
        melodyDensity = melodyDensity,
        rhythmDensity = rhythmDensity,
        harmonicComplexity = harmonicComplexity,
        melodyAnnoying = melodyAnnoying,
        rhythmAnnoying = rhythmAnnoying,
        harmonyLiked = harmonyLiked,
        tooRepetitive = tooRepetitive,
        focusedWell = focusedWell,
        tooDark = tooDark,
        useAgain = useAgain
    )
}

fun FocusSession.toEntity(): FocusSessionEntity = FocusSessionEntity(
    id = id,
    mode = mode.name,
    soundType = soundType.name,
    durationMinutes = durationMinutes,
    elapsedSeconds = elapsedSeconds,
    startedAtMillis = startedAtMillis,
    endedAtMillis = endedAtMillis,
    focusRating = focusRating,
    fatigueRating = fatigueRating,
    brightness = brightness,
    warmth = warmth,
    movement = movement,
    fatigueScore = fatigueScore,
    completed = completed,
    tooBright = tooBright,
    tooMuffled = tooMuffled,
    tooMuchBass = tooMuchBass,
    patchId = patchId,
    patchName = patchName,
    highCut = highCut,
    stereoWidth = stereoWidth,
    rainLayerAmount = rainLayerAmount,
    padLayerAmount = padLayerAmount,
    conditionSnapshotId = conditionSnapshotId,
    compositionPatchId = compositionPatchId,
    compositionPatchName = compositionPatchName,
    compositionGenre = compositionGenre?.name,
    melodyDensity = melodyDensity,
    rhythmDensity = rhythmDensity,
    harmonicComplexity = harmonicComplexity,
    melodyAnnoying = melodyAnnoying,
    rhythmAnnoying = rhythmAnnoying,
    harmonyLiked = harmonyLiked,
    tooRepetitive = tooRepetitive,
    focusedWell = focusedWell,
    tooDark = tooDark,
    useAgain = useAgain
)
